Feature/user interface
afiqaiman98/Correction-Pmint-Inspection-Request pull request #3
Opened 2022-02-15 17:51 UTC by afiqaiman98

User interface added

2022-02-15 18:30 UTC, ImranSasudin requested changes
1. For frontend, please separate navigation header in 1 blade file then include in other blade (request, status and etc)

2. In web.php, please use proper and best practices URL name. for example : 
`GET /inspection/create`
`POST /inspection`
`GET /inspection`
`DELETE /inspection`

![image](https://user-images.githubusercontent.com/51149025/154126071-309762e3-58ca-4cc9-995d-5ad5dbe454c9.png)

2022-02-15 18:30 UTC, ImranSasudin commented on app/Http/Controllers/HomeController.php
> +        $request->file->move('signatureimage',$imagename);
is this file upload working? on my side there is no file uploaded into my local storage

2022-02-15 18:30 UTC, ImranSasudin commented on app/Http/Controllers/HomeController.php
> +        if(Auth::id())
no need to check whether user is logged in or not because if user not logged in, user can't even access to this controller because has been kicked out by middleware

2022-02-15 18:30 UTC, ImranSasudin commented on app/Http/Controllers/HomeController.php
> +        if(Auth::id())
same here, no need to check if user is logged in or not

2022-02-15 20:41 UTC, afiqaiman98 commented on app/Http/Controllers/HomeController.php
> +        if(Auth::id())
user check has been removed

2022-02-15 20:41 UTC, afiqaiman98 commented on app/Http/Controllers/HomeController.php
> +        if(Auth::id())
Check user by Auth removed

2022-02-20 00:07 UTC, ImranSasudin approved these changes
LGTM. Good job!

2022-02-20 00:26 UTC, merged